options:
  merge-default-rules: true

rules:
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1
  no-vendor-prefixes: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
  no-qualifying-elements: 0
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  hex-length:
    - 1
    -
      style: long
  mixins-before-declarations:
    - 2
    -
      exclude:
        - media
        - ie-lte
  no-warn: 1
  no-debug: 1
  no-ids: 0
  no-important: 0
  hex-notation:
    - 1
    -
      style: uppercase
  indentation:
    - 1
    -
      size: 2
  leading-zero: 0
  nesting-depth: 0
  property-sort-order: 0
  shorthand-values: 0
  variable-for-property: 0
